# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e82fd9d642e6ec21569a3450d6c5c323e9acc7905211adce47a8c7ea2e09c5ec66c2d545b5a7f37a914fc1a93478eee257373b02d817852b06d49df376552162

test:
  secret_key_base: 3b013efc992784a90be5582a06578c55f148b13acbc25154465b8b13d00df5836101a5802ccb31548fc270d05f14a579e9474944bf4d208d872db514f0d6e757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
